# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Youri-Package
version:      v0.1.1
version_from: lib/Youri/Package.pm
installdirs:  site
requires:
    Expect:                        0
    RPM4:                          0
    RPM4::Header:                  0
    RPM4::Sign:                    0
    Test::Exception:               0
    UNIVERSAL::require:            0
    URPM:                          0
    version:                       0
    Youri::Package::RPM::Generator: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
